# Generated by Django 3.0.7 on 2020-09-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pac',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.CharField(max_length=100)),
                ('srcIP', models.CharField(max_length=50)),
                ('srcPort', models.IntegerField()),
                ('dstIP', models.CharField(max_length=50)),
                ('dstPort', models.IntegerField()),
                ('protocol', models.CharField(max_length=30)),
                ('length', models.IntegerField()),
                ('info', models.TextField(max_length=300)),
            ],
            options={
                'ordering': ['time'],
            },
        ),
    ]
