# Generated by Django 3.0.7 on 2020-09-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pac',
            name='pcapname',
            field=models.CharField(default='pcap', max_length=100),
        ),
    ]
